# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master"]}

jobs:

  achievements:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: ragdata
          base: achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C          # display achievements of rank C or higher
          plugin_achievements_secrets: yes          # display unlocked secret achievements
          plugin_achievements_display: compact      # use compact display mode
          plugin_achievements_limit: 0              # limit displayed achievements (no limit)

  iso_calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: iso-calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: ragdata
          template: classic
          base: ""
          config_timezone: ${{ secrets.TIMEZONE }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  habits:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: ragdata
          base: ""
          template: classic
          plugin_habits: yes
          plugin_habits_from: 200                   # use 200 events to compute habits
          plugin_habits_days: 14                    # keep only events from the last X days
          plugin_habits_charts: yes                 # display charts section
          plugin_habits_trim: yes                   # trim unused hours on daily chart

  languages:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, qmake, lex, cmake, gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 0

  repositories:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: repositories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: ragdata
          template: classic
          plugin_gists: yes

  wakatime:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: wakatime.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, project-graphs, languages, languages-graphs, editors, os
          #plugin_wakatime_sections: time, projects, project-graphs, languages, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

  sponsorships:
      runs-on: ubuntu-latest
      steps:
        - uses: lowlighter/metrics@latest
          with:
              filename: sponsorships.svg
              token: ${{ secrets.METRICS_TOKEN }}
              base: ""
              plugin_sponsorships: yes
              plugin_sponsorships_sections: amount

  snake:
      runs-on: ubuntu-latest
      steps:
        - uses: Platane/snk@v2
          with:
              github_user_name: ${{ github.repository_owner }}
              outputs: |
                  dist/github-snake.svg
                  dist/github-snake-dark.svg?palette=github-dark
